# Generated by Django 3.0.2 on 2020-02-02 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('shortened_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ShortenedUrl')),
            ],
        ),
    ]
